### ISSUE TITLE
Домашка №0, которую и так все сделали

### ISSUE THREAD

**Issue by tiny-kottan** [GusarL/kottans_homework#1]
1. Установить git / ознакомиться с ним
2. IDE/editor, ознакомиться с ним.
3. DevTools - пройти на CodeSchool (http://discover-devtools.codeschool.com/).
4. Github - завести репозитарий для домашек.
5. GitBranching: http://pcottle.github.io/learnGitBranching/ пройти Main, забросить скриншот в гитхаб, сюда запостить ссылку

**Comment by GusarL** [comment]
http://joxi.ru/4AkzL18Cb5362q
![git branching](https://cloud.githubusercontent.com/assets/13288694/15519714/620560c8-220b-11e6-9fa2-098e792f71ed.gif)
